version: "3.9"
services:
  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    ports:
      - "8081:8081"
    networks:
      - shop-net
  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8082:8082"
    networks:
      - shop-net
  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8080:8080"
    depends_on:
      - inventory-service
      - notification-service
    environment:
      - INVENTORY_URL=http://inventory-service:8081
      - NOTIFICATION_URL=http://notification-service:8082
    networks:
      - shop-net
networks:
  shop-net:
    driver: bridge
